<?php
$j_type=array(
    '1'=>array('算力值结算'),
    '2'=>array('保险公司发币'),
    '3'=>array('移动积分兑换'),
    '4'=>array('邀请用户'),
    '5'=>array('完成任务')
);

$c_type=array(
    '2'=>array('coin'=>50,'msg'=>'使用邀请码注册'),
    '3'=>array('coin'=>10,'msg'=>'邀请码被使用注册'),
    '4'=>array('coin'=>2,'msg'=>'登录'),
    '5'=>array('coin'=>1,'msg'=>'算力'),
);
$jb_type=array(
    '0'=>array('color'=>'green','msg'=>'转入'),
    '1'=>array('color'=>'red','msg'=>'转出'),
    '2'=>array('color'=>'green','msg'=>'日常产出')
);
$task=array(
    '1'=>array(
        'task'=>array(
            '1'=>array(
                'name'=>'每日登陆','coin'=>'3','fz'=>'+3原力','rw_id'=>'1'
            ),
            '2'=>array(
                'name'=>'邀请好友','coin'=>'15','fz'=>'+15原力','rw_id'=>'2'
            )
        ),
        'type'=>'每日任务'
    ),
    '2'=>array(
        'task'=>array(
            '1'=>array(
                'name'=>'成为熊猫会员','coin'=>'2','fz'=>'+2原力','rw_id'=>'3'
            ),
            '2'=>array(
                'name'=>'罚单代缴','coin'=>'2','fz'=>'+2原力','rw_id'=>'4'
            )
        ),
        'type'=>'特殊任务'
    )
);